robosys:
        joint_state_controller:
                type: joint_state_controller/JointStateController
                publish_rate: 50

        diff_drive_controller:
                type: diff_drive_controller/DiffDriveController
                left_wheel: 'left_j'
                right_wheel: 'right_j'
                publish_rate: 50
                pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
                twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]


                wheel_separation: 0.12 
                wheel_radius: 0.08


                wheel_separation_multiplier: 1.0
